export type Language = 'en' | 'vi'

export const copy = {
  en: {
    nav: ['Work', 'About', 'Stack', 'Contact'],
    available: 'Available for internship opportunities',
    role: 'Frontend & Mobile Developer',
    coreStack: 'React · Next.js · TypeScript · Flutter',
    eyebrow: 'Frontend & Mobile Developer',
    heroA: 'I build digital',
    heroB: 'experiences that flow.',
    intro: 'Final-year IT student crafting responsive web interfaces and thoughtful Flutter journeys — from the first interaction to the final API response.',
    explore: 'Explore selected work',
    contactCta: 'Contact me',
    resume: 'Download résumé',
    selected: 'Selected work',
    selectedSub: 'Four products. Different platforms. One focus: making complex flows feel clear.',
    viewLive: 'View live',
    viewCode: 'Source code',
    flagship: 'Flagship mobile experience',
    aboutKicker: 'A little context',
    aboutTitle: 'Beyond the interface.',
    aboutBody: 'I am a final-year IT student focused on frontend development, with hands-on experience building Flutter applications and integrating REST APIs. I care about accessible UI, responsive layouts and practical user flows, and use AI tools to support code review, interface exploration and technical documentation.',
    principle1: 'Design with intent',
    principle1Body: 'Every animation supports hierarchy, feedback or storytelling.',
    principle2: 'Build for real flows',
    principle2Body: 'Authentication, data states, booking, checkout and administration — not isolated screens.',
    education: 'B.Eng. Information Technology',
    school: 'Industrial University of Ho Chi Minh City · 2022 — Present',
    stackKicker: 'Tools I work with',
    stackTitle: 'A practical stack for shipping.',
    contactKicker: 'Have a role or an idea?',
    contactTitleA: 'Let’s build something',
    contactTitleB: 'useful together.',
    contactBody: 'I’m currently looking for Frontend or Mobile Developer internship opportunities in Ho Chi Minh City.',
    email: 'Send an email',
    copied: 'Email copied',
    rights: 'Designed and built by Huynh Gia Huy.',
    additional: 'Additional UI exploration',
    projectRole: 'Role',
    projectProblem: 'Problem solved',
    highlights: 'Highlights',
    caseStudy: 'View case study',
    backToTop: 'Back to top',
  },
  vi: {
    nav: ['Dự án', 'Giới thiệu', 'Kỹ năng', 'Liên hệ'],
    available: 'Sẵn sàng cho cơ hội thực tập',
    role: 'Frontend & Mobile Developer',
    coreStack: 'React · Next.js · TypeScript · Flutter',
    eyebrow: 'Lập trình viên Frontend & Mobile',
    heroA: 'Tôi xây dựng trải nghiệm',
    heroB: 'số mượt mà, rõ ràng.',
    intro: 'Sinh viên CNTT năm cuối, tập trung xây dựng giao diện web responsive và hành trình Flutter chỉn chu — từ tương tác đầu tiên đến phản hồi cuối cùng của API.',
    explore: 'Khám phá dự án',
    contactCta: 'Liên hệ với tôi',
    resume: 'Tải CV',
    selected: 'Dự án tiêu biểu',
    selectedSub: 'Bốn sản phẩm. Nhiều nền tảng. Một mục tiêu: biến quy trình phức tạp thành trải nghiệm rõ ràng.',
    viewLive: 'Xem trực tiếp',
    viewCode: 'Mã nguồn',
    flagship: 'Dự án mobile tiêu biểu',
    aboutKicker: 'Đôi nét về tôi',
    aboutTitle: 'Không chỉ là giao diện.',
    aboutBody: 'Tôi là sinh viên CNTT năm cuối, định hướng Frontend Developer và có kinh nghiệm xây dựng ứng dụng Flutter, tích hợp REST API. Tôi quan tâm đến UI dễ tiếp cận, responsive và luồng người dùng thực tế; đồng thời dùng công cụ AI để hỗ trợ review code, phát triển giao diện và viết tài liệu kỹ thuật.',
    principle1: 'Thiết kế có chủ đích',
    principle1Body: 'Mỗi chuyển động đều phục vụ phân cấp, phản hồi hoặc kể chuyện.',
    principle2: 'Xây dựng luồng thực tế',
    principle2Body: 'Xác thực, trạng thái dữ liệu, đặt phòng, thanh toán và quản trị — không chỉ là các màn hình rời rạc.',
    education: 'Kỹ sư Công nghệ Thông tin',
    school: 'Đại học Công nghiệp TP.HCM · 2022 — Hiện tại',
    stackKicker: 'Công cụ tôi sử dụng',
    stackTitle: 'Công nghệ thực tế để tạo sản phẩm.',
    contactKicker: 'Bạn có cơ hội hoặc ý tưởng?',
    contactTitleA: 'Cùng nhau xây dựng',
    contactTitleB: 'điều gì đó hữu ích.',
    contactBody: 'Tôi đang tìm kiếm cơ hội thực tập Frontend hoặc Mobile Developer tại TP. Hồ Chí Minh.',
    email: 'Gửi email',
    copied: 'Đã sao chép email',
    rights: 'Thiết kế và phát triển bởi Huỳnh Gia Huy.',
    additional: 'Khám phá UI bổ sung',
    projectRole: 'Vai trò',
    projectProblem: 'Vấn đề giải quyết',
    highlights: 'Điểm nổi bật',
    caseStudy: 'Xem case study',
    backToTop: 'Về đầu trang',
  },
} as const

export const projects = [
  {
    id: 'stayz',
    index: '01',
    year: '2026',
    title: 'StayZ',
    role: { en: 'Mobile Developer', vi: 'Lập trình viên Mobile' },
    problem: {
      en: 'Turn a fragmented hotel search and booking process into one guided mobile journey.',
      vi: 'Kết nối quá trình tìm kiếm và đặt phòng rời rạc thành một hành trình mobile liền mạch.',
    },
    highlights: {
      en: ['30+ responsive screens', '15+ REST integrations', 'PayOS + AI booking flows'],
      vi: ['30+ màn hình responsive', '15+ tích hợp REST API', 'Luồng PayOS + trợ lý AI'],
    },
    type: { en: 'Hotel booking · Flutter', vi: 'Đặt phòng khách sạn · Flutter' },
    description: {
      en: 'Built a 30+ screen Flutter booking experience spanning customer and admin journeys, with 15+ REST integrations, a six-stage reservation flow, PayOS QR payments and AI-assisted hotel search.',
      vi: 'Xây dựng trải nghiệm đặt phòng Flutter hơn 30 màn hình cho cả khách hàng và quản trị, tích hợp hơn 15 REST API, quy trình đặt phòng 6 giai đoạn, thanh toán QR PayOS và tìm kiếm hỗ trợ bởi AI.',
    },
    stats: ['30+ screens', '6-stage booking', '15+ API operations'],
    tags: ['Flutter', 'Dart', 'REST API', 'PayOS'],
    github: 'https://github.com/huynhgiahuy236/stayz-mobile-app',
    live: '',
    visual: 'phone',
  },
  {
    id: 'movie',
    index: '02',
    year: '2026',
    title: 'Movie Booking',
    role: { en: 'Frontend Developer', vi: 'Lập trình viên Frontend' },
    problem: {
      en: 'Make showtime discovery, seat selection and administration clear within one responsive platform.',
      vi: 'Làm rõ luồng tìm suất chiếu, chọn ghế và quản trị trong một nền tảng responsive.',
    },
    highlights: {
      en: ['Role-protected routes', 'Interactive seat state', 'Customer + Admin CRUD'],
      vi: ['Phân quyền route', 'Trạng thái ghế tương tác', 'CRUD khách hàng + quản trị'],
    },
    type: { en: 'Entertainment platform · React', vi: 'Nền tảng giải trí · React' },
    description: {
      en: 'Developed responsive customer and admin flows for movie discovery, showtimes and seat booking, with synchronized seat states, protected routes and reusable CRUD management interfaces.',
      vi: 'Phát triển luồng khách hàng và quản trị responsive cho tìm phim, suất chiếu và đặt ghế; đồng bộ trạng thái ghế, bảo vệ route và tái sử dụng giao diện CRUD quản lý.',
    },
    stats: ['Customer + Admin', 'Seat booking', 'Role-based access'],
    tags: ['ReactJS', 'Redux Toolkit', 'TanStack Query', 'Tailwind'],
    github: 'https://github.com/huynhgiahuy236/capstone_reactjs',
    live: 'https://capstone-movie-ten.vercel.app/',
    visual: 'cinema',
  },
  {
    id: 'shoes',
    index: '03',
    year: '2026',
    title: 'HiKu Shoes',
    role: { en: 'Frontend Developer', vi: 'Lập trình viên Frontend' },
    problem: {
      en: 'Keep storefront, cart, inventory and order states consistent across customer and admin flows.',
      vi: 'Đồng bộ trạng thái cửa hàng, giỏ hàng, tồn kho và đơn hàng giữa khách hàng và quản trị.',
    },
    highlights: {
      en: ['Synchronized cart state', 'Inventory + order workflow', 'Sales analytics dashboard'],
      vi: ['Đồng bộ trạng thái giỏ hàng', 'Luồng tồn kho + đơn hàng', 'Dashboard phân tích doanh thu'],
    },
    type: { en: 'Commerce system · React', vi: 'Hệ thống thương mại · React' },
    description: {
      en: 'Engineered a complete storefront and admin system that keeps cart, checkout, inventory and order states consistent across customer and management workflows.',
      vi: 'Xây dựng hệ thống cửa hàng và quản trị hoàn chỉnh, giữ trạng thái giỏ hàng, thanh toán, tồn kho và đơn hàng nhất quán giữa luồng khách hàng và quản lý.',
    },
    stats: ['Cart + Checkout', 'Inventory', 'Admin analytics'],
    tags: ['ReactJS', 'Redux Toolkit', 'React Query', 'Axios'],
    github: 'https://github.com/huynhgiahuy236/ShoesStore_ReactJS',
    live: 'https://shoes-store-react-js.vercel.app/',
    visual: 'shoe',
  },
  {
    id: 'phone',
    index: '04',
    year: '2026',
    title: 'HiKu Phone',
    role: { en: 'Frontend Developer', vi: 'Lập trình viên Frontend' },
    problem: {
      en: 'Build a maintainable commerce workflow using vanilla JavaScript and persistent browser data.',
      vi: 'Xây dựng luồng thương mại dễ bảo trì bằng JavaScript thuần và dữ liệu lưu trên trình duyệt.',
    },
    highlights: {
      en: ['Vanilla JS architecture', 'Persistent browser state', 'MockAPI CRUD + Excel export'],
      vi: ['Kiến trúc JavaScript thuần', 'Trạng thái lưu trên trình duyệt', 'MockAPI CRUD + xuất Excel'],
    },
    type: { en: 'E-commerce · JavaScript', vi: 'Thương mại điện tử · JavaScript' },
    description: {
      en: 'Structured a maintainable vanilla JavaScript commerce application with MockAPI CRUD, authentication, persistent browser state, checkout, inventory management and Excel reporting.',
      vi: 'Tổ chức ứng dụng thương mại JavaScript thuần dễ bảo trì với MockAPI CRUD, xác thực, trạng thái lưu trên trình duyệt, thanh toán, quản lý tồn kho và báo cáo Excel.',
    },
    stats: ['Vanilla JavaScript', 'MockAPI CRUD', 'Excel export'],
    tags: ['JavaScript', 'Tailwind CSS', 'MockAPI', 'LocalStorage'],
    github: '',
    live: 'https://phone-store-js-html-tailwindcss.vercel.app/',
    visual: 'device',
  },
] as const
