export type Language = 'en' | 'vi'

export const copy = {
  en: {
    nav: ['Work', 'About', 'Stack', 'Contact'],
    available: 'Available for internship opportunities',
    eyebrow: 'Frontend & Mobile Developer',
    heroA: 'I build digital',
    heroB: 'experiences that flow.',
    intro: 'Final-year IT student crafting responsive web interfaces and thoughtful Flutter journeys — from the first interaction to the final API response.',
    explore: 'Explore selected work',
    resume: 'Download résumé',
    selected: 'Selected work',
    selectedSub: 'Four products. Different platforms. One focus: making complex flows feel clear.',
    viewLive: 'View live',
    viewCode: 'Source code',
    flagship: 'Flagship mobile experience',
    aboutKicker: 'A little context',
    aboutTitle: 'Beyond the interface.',
    aboutBody: 'I enjoy the space where visual craft, application state and real API workflows meet. My work spans customer experiences and admin systems, with a focus on structure, responsiveness and practical product flows.',
    principle1: 'Design with intent',
    principle1Body: 'Every animation supports hierarchy, feedback or storytelling.',
    principle2: 'Build for real flows',
    principle2Body: 'Authentication, data states, booking, checkout and administration — not isolated screens.',
    education: 'B.Eng. Information Technology',
    school: 'Industrial University of Ho Chi Minh City · 2022 — Present',
    stackKicker: 'Tools I work with',
    stackTitle: 'A practical stack for shipping.',
    contactKicker: 'Have a role or an idea?',
    contactTitleA: 'Let’s build something',
    contactTitleB: 'useful together.',
    contactBody: 'I’m currently looking for Frontend or Mobile Developer internship opportunities in Ho Chi Minh City.',
    email: 'Send an email',
    copied: 'Email copied',
    rights: 'Designed and built by Huynh Gia Huy.',
    additional: 'Additional UI exploration',
  },
  vi: {
    nav: ['Dự án', 'Giới thiệu', 'Kỹ năng', 'Liên hệ'],
    available: 'Sẵn sàng cho cơ hội thực tập',
    eyebrow: 'Lập trình viên Frontend & Mobile',
    heroA: 'Tôi xây dựng trải nghiệm',
    heroB: 'số mượt mà, rõ ràng.',
    intro: 'Sinh viên CNTT năm cuối, tập trung xây dựng giao diện web responsive và hành trình Flutter chỉn chu — từ tương tác đầu tiên đến phản hồi cuối cùng của API.',
    explore: 'Khám phá dự án',
    resume: 'Tải CV',
    selected: 'Dự án tiêu biểu',
    selectedSub: 'Bốn sản phẩm. Nhiều nền tảng. Một mục tiêu: biến quy trình phức tạp thành trải nghiệm rõ ràng.',
    viewLive: 'Xem trực tiếp',
    viewCode: 'Mã nguồn',
    flagship: 'Dự án mobile tiêu biểu',
    aboutKicker: 'Đôi nét về tôi',
    aboutTitle: 'Không chỉ là giao diện.',
    aboutBody: 'Tôi yêu thích điểm giao nhau giữa thẩm mỹ, trạng thái ứng dụng và luồng API thực tế. Công việc của tôi trải dài từ trải nghiệm khách hàng đến hệ thống quản trị, với trọng tâm là cấu trúc, responsive và quy trình sản phẩm thực tiễn.',
    principle1: 'Thiết kế có chủ đích',
    principle1Body: 'Mỗi chuyển động đều phục vụ phân cấp, phản hồi hoặc kể chuyện.',
    principle2: 'Xây dựng luồng thực tế',
    principle2Body: 'Xác thực, trạng thái dữ liệu, đặt phòng, thanh toán và quản trị — không chỉ là các màn hình rời rạc.',
    education: 'Kỹ sư Công nghệ Thông tin',
    school: 'Đại học Công nghiệp TP.HCM · 2022 — Hiện tại',
    stackKicker: 'Công cụ tôi sử dụng',
    stackTitle: 'Công nghệ thực tế để tạo sản phẩm.',
    contactKicker: 'Bạn có cơ hội hoặc ý tưởng?',
    contactTitleA: 'Cùng nhau xây dựng',
    contactTitleB: 'điều gì đó hữu ích.',
    contactBody: 'Tôi đang tìm kiếm cơ hội thực tập Frontend hoặc Mobile Developer tại TP. Hồ Chí Minh.',
    email: 'Gửi email',
    copied: 'Đã sao chép email',
    rights: 'Thiết kế và phát triển bởi Huỳnh Gia Huy.',
    additional: 'Khám phá UI bổ sung',
  },
} as const

export const projects = [
  {
    id: 'stayz',
    index: '01',
    year: '2026',
    title: 'StayZ',
    type: { en: 'Hotel booking · Flutter', vi: 'Đặt phòng khách sạn · Flutter' },
    description: {
      en: 'A 30+ screen Flutter experience with hotel discovery, a six-stage booking journey, PayOS payments, post-stay reviews and three admin modules.',
      vi: 'Ứng dụng Flutter hơn 30 màn hình với tìm kiếm khách sạn, quy trình đặt phòng 6 giai đoạn, thanh toán PayOS, đánh giá sau lưu trú và 3 module quản trị.',
    },
    stats: ['30+ screens', '6-stage booking', '15+ API operations'],
    tags: ['Flutter', 'Dart', 'REST API', 'PayOS'],
    github: 'https://github.com/huynhgiahuy236/stayz-mobile-app',
    live: '',
    visual: 'phone',
  },
  {
    id: 'movie',
    index: '02',
    year: '2026',
    title: 'Movie Booking',
    type: { en: 'Entertainment platform · React', vi: 'Nền tảng giải trí · React' },
    description: {
      en: 'A responsive customer and admin platform featuring discovery, trailers, showtimes, interactive seat selection, protected routes and management workflows.',
      vi: 'Nền tảng khách hàng và quản trị responsive với tìm kiếm phim, trailer, suất chiếu, chọn ghế tương tác, protected routes và các luồng quản lý.',
    },
    stats: ['Customer + Admin', 'Seat booking', 'Role-based access'],
    tags: ['ReactJS', 'Redux Toolkit', 'TanStack Query', 'Tailwind'],
    github: 'https://github.com/huynhgiahuy236/capstone_reactjs',
    live: 'https://capstone-movie-ten.vercel.app/',
    visual: 'cinema',
  },
  {
    id: 'shoes',
    index: '03',
    year: '2026',
    title: 'HiKu Shoes',
    type: { en: 'Commerce system · React', vi: 'Hệ thống thương mại · React' },
    description: {
      en: 'A complete storefront and admin experience with search, cart, wishlist, checkout, inventory, order processing, reviews and sales statistics.',
      vi: 'Trải nghiệm cửa hàng và quản trị với tìm kiếm, giỏ hàng, yêu thích, thanh toán, tồn kho, xử lý đơn, đánh giá và thống kê doanh thu.',
    },
    stats: ['Cart + Checkout', 'Inventory', 'Admin analytics'],
    tags: ['ReactJS', 'Redux Toolkit', 'React Query', 'Axios'],
    github: 'https://github.com/huynhgiahuy236/ShoesStore_ReactJS',
    live: 'https://shoes-store-react-js.vercel.app/',
    visual: 'shoe',
  },
  {
    id: 'phone',
    index: '04',
    year: '2026',
    title: 'HiKu Phone',
    type: { en: 'E-commerce · JavaScript', vi: 'Thương mại điện tử · JavaScript' },
    description: {
      en: 'A responsive JavaScript storefront powered by MockAPI, with authentication, persistent cart, wishlist, checkout, admin inventory and Excel reports.',
      vi: 'Cửa hàng JavaScript responsive sử dụng MockAPI, có xác thực, giỏ hàng lưu trữ, yêu thích, thanh toán, quản trị tồn kho và xuất báo cáo Excel.',
    },
    stats: ['Vanilla JavaScript', 'MockAPI CRUD', 'Excel export'],
    tags: ['JavaScript', 'Tailwind CSS', 'MockAPI', 'LocalStorage'],
    github: '',
    live: 'https://phone-store-js-html-tailwindcss.vercel.app/',
    visual: 'device',
  },
] as const
